workspace(name = "projectA")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
  name = "nlohmann_json",
  url = "https://github.com/nlohmann/json/archive/v3.11.3.tar.gz",
  strip_prefix = "json-3.11.3",
)
